# Site settings
title: 季陆的博客
email: liuchunmeng666@163.com
keyword: "季陆的博客, 季陆, soulcm, soulcm blog, 刘淳猛, 前端开发, 博客"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: soulcm
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "page:num"

exclude: ["README.md"]
